version: "3.7"
services:
  metricq-python:
    image: metricq-python
    build:
      context: https://github.com/metricq/metricq.git#docker-test
      dockerfile: Dockerfile-python
    networks:
      - metricq-network

  metricq-manager:
    build:
      context: https://github.com/metricq/metricq-manager.git#docker-test
    environment:
      wait_for_couchdb_url: "couchdb-server:5984"
      couchdb_url: "http://couchdb-server:5984"
      couchdb_user: "admin"
      couchdb_pw: "admin"
      wait_for_rabbitmq_url: "rabbitmq-server:5672"
      rpc_url: "amqp://rabbitmq:rabbitmq@rabbitmq-server/"
      data_url: "amqp://rabbitmq:rabbitmq@rabbitmq-server/"
    volumes:
      - "./config:/home/metricq/manager/config"
    depends_on:
      - rabbitmq-server
      - couchdb-server
    networks:
      - metricq-network

  metricq-cxx:
    image: metricq-cxx
    build:
      context: https://github.com/metricq/metricq.git#docker-test
      dockerfile: Dockerfile-cxx
    networks:
      - metricq-network

  rabbitmq-server:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - metricq-network

  couchdb-server:
    image: couchdb
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
    networks:
      - metricq-network

networks:
  metricq-network:
    driver: bridge
